### ISSUE TITLE
form-field: document new features for 6.0.0

### ISSUE THREAD

**Issue by mmalerba** [angular/material2#10222]
- [x] New appearance option #9762
- [x] Allow `type=color` #8748
- [x] `AutofillMonitor` and autofill Sass mixins #9831
